name: Presentation
on: 
  push:
jobs:
  presentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run latex
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd tex
            pdflatex -file-line-error -interaction=nonstopmode git_course.tex
            pdflatex -file-line-error -interaction=nonstopmode git_course.tex
            mv git_course.pdf ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Git Course
          body: Slides on pdf
          files: git_course.pdf
